/*
 * generated by Xtext
 */
package org.eclipse.gef.dot.internal.ui.language.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class DotEscStringProposalProvider extends org.eclipse.gef.dot.internal.ui.language.contentassist.AbstractDotEscStringProposalProvider {

}
