/*
* generated by Xtext
*/
package org.eclipse.gef.dot.internal.ui.language.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class DotRectProposalProvider extends org.eclipse.gef.dot.internal.ui.language.contentassist.AbstractDotRectProposalProvider {

}
