/*
* generated by Xtext
*/
package org.eclipse.zest.internal.dot.parser.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DotAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/zest/internal/dot/parser/parser/antlr/internal/InternalDot.tokens");
	}
}
