/*
 * generated by Xtext 2.17.0
 */
package org.eclipse.gef.dot.internal.ui.language.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class DotColorOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
