/*
 * generated by Xtext 2.17.0
 */
package org.eclipse.gef.dot.tests

import com.google.inject.Inject
import org.eclipse.gef.dot.internal.language.splinetype.SplineType
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DotSplineTypeInjectorProvider)
class DotSplineTypeParsingTest {
	@Inject
	ParseHelper<SplineType> parseHelper
	
}
