/*
* generated by Xtext
*/
package org.eclipse.gef.dot.internal.language.validation;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class DotRectJavaValidator extends org.eclipse.gef.dot.internal.language.validation.AbstractDotRectJavaValidator {

//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
//		}
//	}
}
