/*
 * generated by Xtext
 */
package org.eclipse.gef.dot.internal.ui.language;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DotEscStringUiModule extends org.eclipse.gef.dot.internal.ui.language.AbstractDotEscStringUiModule {
	public DotEscStringUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
