/*
 * generated by Xtext
 */
package org.eclipse.gef.dot.internal.ui.language;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DotRectUiModule extends org.eclipse.gef.dot.internal.ui.language.AbstractDotRectUiModule {
	public DotRectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
