/*
 * generated by Xtext
 */
package org.eclipse.gef.dot.internal.language.formatting;

import org.eclipse.gef.dot.internal.language.services.DotEscStringGrammarAccess;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

import com.google.inject.Inject;

/**
 * This class contains custom formatting declarations.
 */
public class DotEscStringFormatter extends AbstractDeclarativeFormatter {

	@Inject
	private DotEscStringGrammarAccess grammarAccess;

	@Override
	protected void configureFormatting(FormattingConfig c) {
	}
}