<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dot"
    nsURI="http://www.eclipse.org/zest/internal/dot/parser/Dot" nsPrefix="dot">
  <eClassifiers xsi:type="ecore:EClass" name="GraphvizModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphs" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//MainGraph"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainGraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strict" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//GraphType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmts" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Stmt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stmt"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeStmtNode" eSuperTypes="platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node_id" eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//NodeId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeRHS" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//EdgeRhs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//AttrList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeStmtSubgraph" eSuperTypes="platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subgraph" eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Subgraph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeRHS" eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//EdgeRhs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//AttrList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeStmt" eSuperTypes="platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//AttrList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrStmt" eSuperTypes="platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//AttributeType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//AttrList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a_list" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//AList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subgraph" eSuperTypes="platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmts" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Stmt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeRhs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EEnum platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//EdgeOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeRhsNode" eSuperTypes="platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//EdgeRhs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//NodeId"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeRhsSubgraph" eSuperTypes="platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//EdgeRhs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subgraph" eType="ecore:EClass platform:/resource/org.eclipse.zest.dot.core/src-gen/org/eclipse/zest/internal/dot/parser/Dot.ecore#//Subgraph"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EdgeOp">
    <eLiterals name="directed" literal="->"/>
    <eLiterals name="undirected" value="1" literal="--"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GraphType">
    <eLiterals name="graph" literal="graph"/>
    <eLiterals name="digraph" value="1" literal="digraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeType">
    <eLiterals name="graph" literal="graph"/>
    <eLiterals name="node" value="1" literal="node"/>
    <eLiterals name="edge" value="2" literal="edge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompassPt">
    <eLiterals name="north" literal="n"/>
    <eLiterals name="northeast" value="1" literal="ne"/>
    <eLiterals name="east" value="2" literal="e"/>
    <eLiterals name="southeast" value="3" literal="se"/>
    <eLiterals name="south" value="4" literal="s"/>
    <eLiterals name="southwest" value="5" literal="sw"/>
    <eLiterals name="west" value="6" literal="w"/>
    <eLiterals name="northwest" value="7" literal="nw"/>
  </eClassifiers>
</ecore:EPackage>
