/*
 * generated by Xtext
 */
package org.eclipse.gef.dot.internal.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DotRectRuntimeModule extends org.eclipse.gef.dot.internal.language.AbstractDotRectRuntimeModule {

}
