/*
 * generated by Xtext
 */
package org.eclipse.gef4.dot.internal.parser.validation;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DotSplineTypeJavaValidator extends org.eclipse.gef4.dot.internal.parser.validation.AbstractDotSplineTypeJavaValidator {

//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
//		}
//	}
}
