/*
 * generated by Xtext 2.17.0
 */
package org.eclipse.gef.dot.internal.ide.language;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.gef.dot.internal.language.DotColorRuntimeModule;
import org.eclipse.gef.dot.internal.language.DotColorStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DotColorIdeSetup extends DotColorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DotColorRuntimeModule(), new DotColorIdeModule()));
	}
	
}
