/*
 * generated by Xtext 2.17.0
 */
package org.eclipse.gef.dot.internal.ide.language;


/**
 * Use this class to register ide components.
 */
public class DotPointIdeModule extends AbstractDotPointIdeModule {
}
