/*
 * generated by Xtext
 */
package org.eclipse.gef4.dot.internal.parser;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DotShapeStandaloneSetup extends DotShapeStandaloneSetupGenerated{

	public static void doSetup() {
		new DotShapeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

