/*
 * generated by Xtext
 */
package org.eclipse.gef4.dot.internal.parser;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DotStyleRuntimeModule extends org.eclipse.gef4.dot.internal.parser.AbstractDotStyleRuntimeModule {

}
