/*
 * generated by Xtext
 */
package org.eclipse.gef4.dot.internal.parser.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DotStyleUiModule extends org.eclipse.gef4.dot.internal.parser.ui.AbstractDotStyleUiModule {
	public DotStyleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
