/*
 * generated by Xtext
 */
package org.eclipse.zest.internal.dot.parser.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.zest.internal.dot.parser.DotParserActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.zest.internal.dot.parser.DotParserActivator.getInstance().getInjector("org.eclipse.zest.internal.dot.parser.Dot");
	}
	
}
